// <auto-generated />
using HealthApp.Data.Workout;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HealthApp.Migrations
{
    [DbContext(typeof(Workout_Context))]
    [Migration("20230130134202_Create_Workout_Table")]
    partial class Create_Workout_Table
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HealthApp.Data.Workout.Workout", b =>
                {
                    b.Property<int>("Workout_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Workout_Activity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Workout_Time")
                        .HasColumnType("int");

                    b.HasKey("Workout_ID");

                    b.ToTable("Workouts");
                });
#pragma warning restore 612, 618
        }
    }
}
